name: MGLib
version: 0.4.3-SNAPSHOT
main: net.amigocraft.mglib.Main
description: A Bukkit library designed to ease the process of minigame plugin creation.
author: Maxim Roncacé

commands:
  mglib:
    description: The primary command for the library.
    usage: /mglib