# ####################### #
# # MGLib Configuration # #
# ####################### #

# When true, MGLib will log block changes in arenas immediately.
# When false, block change data is saved when a round ends.
# If you set this to false, you may see a slight performance increase, but if the server crashes, changes since the
# last round end will be lost.
# We highly recommend you leave this at its default value (true).
immediate-logging: true

# When the following protections are enabled, certain block events will be cancelled in worlds containing arenas.
# Please note that if left as false, these actions *will not be rolled back*.
protections:
    burn: true
    fade: true
    grow: true
    ignite: true
    liquidFlow: false
    melt: true
    physics: true
    piston: false
    spread: true

# Should MGLib silently download and install updates when available?
# We highly recommend you set this to true so you may run plugins using new features.
enable-updater: true

# Should MGLib submit anonymous statistics to MCStats? (Set to false if you're paranoid.)
enable-metrics: true